name: flutter_app_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg
    - assets/images/image4.jpg

  # Extra-bold: 800,
  # Bold: 700,
  # Semi-bolt: 600,
  # medium: 500,
  # regular: 400,
  # light: 300

  fonts:
    # spell-checker: disable
    - family: HindSiliguri
      fonts:
        - asset: assets/fonts/HindSiliguri-Bold.ttf
        - asset: assets/fonts/HindSiliguri-SemiBold.ttf
        - asset: assets/fonts/HindSiliguri-Medium.ttf
        - asset: assets/fonts/HindSiliguri-Regular.ttf
        - asset: assets/fonts/HindSiliguri-Light.ttf
    # spell-checker: enable

    # spell-checker: disable
    - family: Doto
      fonts:
        - asset: assets/fonts/Doto.ttf
  # spell-checker: enable

  # - family: NotoSerif
  #   fonts:
  #     - asset: assets/fonts/NotoSerif-Italic-VariableFont_wght,wght.ttf
  #       style: italic
  #     # - asset: assets/fonts/NotoSerif-VariabelFont_wght,wght.ttf
  #     #   weight: 400
  # - family: PlayfairDisplay
  #   fonts:
  #     - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
  #       style: italic
  #     - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
  #       weight: 400
